added some tests
Mstrutov/CSC_SoftwareArchitecture pull request #15
Opened 2022-03-04 23:32 UTC by F03000

2022-03-05 12:54 UTC, Mstrutov requested changes

2022-03-05 12:54 UTC, Mstrutov commented on hw1/src/main/java/parsing/QuoteParser.java
> +                    if (!currentString.isEmpty()) {
Тут бы конечно вынести четыре почти одинаковых куска в функцию. Чтобы обобщить конструктор, можно его параметром прокидывать.

2022-03-05 12:54 UTC, Mstrutov commented on hw1/src/test/java/executing/ExecutorTest.java
> +public class ExecutorTest {
У тебя тут интеграционные тесты получились -- они тоже очень нужны, но надо по-хорошему по другому класс назвать. Типа `IntegrationTest`. Это даже наверное не только на `Executor` тесты, потому что ты проверяешь и результат парсинга (`getExecutablesFromString`)

2022-03-06 09:11 UTC, Mstrutov commented on hw1/src/main/java/execution/commands/Cat.java
> +        } finally {
finally лишний видимо

2022-03-06 09:11 UTC, Mstrutov commented on hw1/src/main/java/parsing/QuoteParser.java
> +        int boundIndex = 0;
boundIndex бы как-то по-другому назвать, сходу непонятно, что мы так запоминаем RawString.

`unquotedStartIndex`?

2022-03-06 09:11 UTC, Mstrutov commented on hw1/src/main/java/parsing/QuoteParser.java
> +                i = nextFullIndex + 1;
1. Хочется внести вычисление индекса внутрь if-а, чтобы каждый раз дважды не вычислять. Типа 
  ```
  if (ch == '\'') {
    int nextFullIndex = ...
    ...
  } else if (ch == '"') {
    int nextWeakIndex = ...
    ...
  }
  ```
2. Опять же, обе ветки очень похожие -- отличаются только конструктором и '/". Их бы вынести в отдельную функцию, типа `parseToNextQuotation(...)`. Можно сделать, чтобы она возвращала nextIndex, тогда можно будет обновить i, boundIndex. 
  Это, по-моему, улучшит читаемость, но вообще некритично -- если не получится, можно так оставить.

2022-03-06 09:11 UTC, Mstrutov commented on hw1/src/test/java/parsing/QuoteParserTest.java
> +        testString("", Collections.emptyList());
По-хорошему, это должны быть разные тест кейсы с говорящими названиями.

Типа
```
testSingleFullQuotationParsesAsRaw() {
  ...
}
testWeakQuotationParsesAsWeakQuoted() {
  ...
}
...
```

Может показаться, что это какое-то чрезмерное дублирование и лишний код, но тесты должны
- покрывать разные случаи и показывать, с какими компонента не справляется -- поэтому надо разделять на отдельные тест кейсы
- быть говорящими, демонстрировать правильное поведение компоненты, служить своего рода документацией -- поэтому надо придумывать говорящие названия, чтобы потом, пробежавшись взглядом по тестам, можно было понять из одних названий, как ведёт себя компонента, не вглядываясь в реализацию тестов

2022-03-06 09:11 UTC, Mstrutov commented on hw1/src/test/java/parsing/QuoteParserTest.java
> +    public void testString(String str, List<QuoteProcessedString> actualList) {
testStringsAreEqual

2022-03-06 09:11 UTC, Mstrutov commented on hw1/src/test/java/parsing/ReaderTest.java
> +public class ReaderTest {
Вот это ты придумал, лайк!

2022-03-06 09:11 UTC, Mstrutov commented on hw1/src/test/java/parsing/ReaderTest.java
> +        Random randomGenerator = new Random();
Random лучше снаружи создавать, а не каждый раз при генерации случайного числа. Можно static полем класса.

И ещё, обязательно надо делать это так:
```
// псевдокод
int seed = randomInt();
Random generator = new Random(seed):
print(seed)
``` 
Это нужно для воспроизводимости. Если вдруг тесты упадут, надо уметь воспроизвести случайную строку, на которой они упали. `new Random(seed)` с тем же seed выдаст ту же последовательность, поэтому это будет просто. Без seed придётся заново перепрогонять, пока не встретится примерно такая же строчка -- это может быть долго.

2022-03-06 09:11 UTC, Mstrutov commented on hw1/src/test/java/parsing/ReaderTest.java
> +public class ReaderTest {
Здорово бы этот подход ещё в integrationTest использовать, чтобы проверить, что NinB никогда не падает целиком.

2022-03-06 10:20 UTC, F03000 commented on hw1/src/main/java/parsing/QuoteParser.java
> +                i = nextFullIndex + 1;
Я не смог это сделать быстро, потому что хотел сделать красиво - передать класс и создать его инстанс в методе, но это сделать быстро у меня не получилось. Если у тебя будет время и ты это сделаешь - отлично

2022-03-06 11:25 UTC, Mstrutov approved these changes

2022-03-06 11:25 UTC, merged